### ISSUE TITLE
sass or css select setup

### ISSUE THREAD

**Issue by joshmedeski** [productdevbook/nuxt3-app#17]
### Environment

Nuxt CLI v3.0.0-27242401.39ed77e                                                             
RootDir: /Users/joshmedeski/Downloads/nuxt3-
Nuxt project info:                                                                           

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.11.1`
- Nuxt Version:     `3-3.0.0-27242401.39ed77e`
- Package Manager:  `Yarn`
- Bundler:          `Webpack`
- User Config:      `buildModules`, `build`
- Runtime Modules:  `-`
- Build Modules:    `@pinia/nuxt@0.0.6`
------------------------------

### Describe the bug

Your `nuxt.config.ts` file references PostCSS, but I see that you also have Sass installed. Only one of these tools needs to be chosen for compiling the TailwindCSS code.

TailwindCSS [recommends](https://tailwindcss.com/docs/guides/nuxtjs) PostCSS. Removing the `sass` and `sass-loader` packages and switching your global CSS file to `.css` will make your project have faster install times.

### Additional context

If I'm missing something please let me know, but I read through all the code and saw no reference to Sass aside from the `package.json` file.

**Comment by joshmedeski** [comment]
`@apply` is a PostCSS feature provided by Tailwind's PostCSS config 😸

**Comment by productdevbook** [comment]
> `@apply` is a PostCSS feature provided by Tailwind's PostCSS config 😸

I know this. :D I have not used Postcss before. And right now that got me confused. How is it different from Sass?

You say `If I'm missing something please let me know, but I read through all the code and saw no reference to Sass aside from the package.json file.`

I showed the place where it was written. :D

**Comment by productdevbook** [comment]
Thank you for showing me this.
I understand what you are saying, I will type a terminal command. You will choose sass or css for installation.

**Comment by joshmedeski** [comment]
I see it now, thanks. It seems that Nuxt supports sass with that syntax, however, it's not necessary to use it since you're using TailwindCSS with PostCSS. Hope it helps.
