### ISSUE TITLE
Got FATAL ERROR: v8::FromJust Maybe value is Nothing

### ISSUE THREAD

**Issue by minyou9** [productdevbook/nuxt3-app#27]
### Environment

- Package Manager:  `yarn@1.22.15`
- Bundler:          `Webpack`
- User Config:      `buildModules`, `build`
- Runtime Modules:  `-`
- Build Modules:    `@pinia/nuxt@0.1.5`

### Describe the bug

I got the errors after refreshing the browser 5-8 times while debugging the css tailwind class

### Additional context

FATAL ERROR: v8::FromJust Maybe value is Nothing.
 1: 00007FF6B207013F v8::internal::CodeObjectRegistry::~CodeObjectRegistry+112495
 2: 00007FF6B1FFF396 DSA_meth_get_flags+65526
 3: 00007FF6B200024D node::OnFatalError+301
 4: 00007FF6B291C2F5 v8::V8::FromJustIsNothing+53
 5: 00007FF6B1FE83E3 v8::base::CPU::has_sse+31491
 8: 00007FF6B20CE9EC uv_loop_init+1292
 9: 00007FF6B20CEB8A uv_run+202
10: 00007FF6B209DC95 node::SpinEventLoop+309
11: 00007FF6B1F38660 v8::internal::wasm::SignatureMap::Freeze+35776
12: 00007FF6B1F33CB8 v8::internal::wasm::SignatureMap::Freeze+16920
13: 00007FF6B20BF36D uv_poll_stop+557
14: 00007FF6B2ED0C60 v8::internal::compiler::RepresentationChanger::Uint32OverflowOperatorFor+146416
15: 00007FFA7EF154E0 BaseThreadInitThunk+16
16: 00007FFA7FC6485B RtlUserThreadStart+43

**Comment by productdevbook** [comment]
I couldn't reproduce the same problem.

**Comment by productdevbook** [comment]
please test v1.5.0
