### ISSUE TITLE
unable to run preview or start

### ISSUE THREAD

**Issue by billysean** [productdevbook/nuxt3-app#31]
### Environment

Nuxt CLI v3.0.0-27376943.f219f63                                                                                                                     
RootDir: D:\project\nuxt3TemplateTailwind                                                                                                            
Nuxt project info:                                                                                                                                     

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v14.18.1`
- Nuxt Version:     `3.0.0-27376943.f219f63`
- Package Manager:  `npm@8.1.1`
- Bundler:          `Vite`
- User Config:      `css`, `build`, `publicRuntimeConfig`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Describe the bug

INFO : This error is generated purely by cloning this git

ERROR DESC : building was successful but generates error when trying to run `npm run start`

'D:\project\test\nuxt3-app\.output\server\node_modules\@heroicons\vue\outline' is not supported resolving ES modules imported from D:\project\test\nuxt3-app\.output\server\chunks\server2.mjs

both for @heroicons/vue & @headlessui/vue generates this error

**Comment by nikita-komissarov** [comment]
I'm already sent a pull request for this
If you need an **immediately fix** on this:

In file `nuxt.config.ts`
Add `transpile: ['@heroicons/vue']` in `build` section, before postcss e.g.
Finally run `yarn build` and `yarn start`

Full `nuxt.conf.ts` for example:
```
import { defineNuxtConfig } from "nuxt3";

export default defineNuxtConfig({
    buildModules: [
        // pinia plugin - https://pinia.esm.dev
        "@pinia/nuxt",
    ],
    build: {
        transpile: ['@heroicons/vue'],
        postcss: {
            postcssOptions: {
                plugins: {
                    tailwindcss: {},
                    autoprefixer: {},
                },
            },
        },
    },
    vite: {
        logLevel: "info",
        optimizeDeps: {
            include: [
                '@headlessui/vue', '@heroicons/vue/solid', '@heroicons/vue/outline', 'vue', 'pinia'
            ]
        }
    }
});
```
